swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /users:
    get:
      tags:
        - User
      operationId: application.endpoint_handler_user.read_all
      summary: Read the entire set of user.
      description: Read the entire set of user
      responses:
        '200':
          description: Successfully read user set operation

    post:
      operationId: application.endpoint_handler_user.add_one
      tags:
        - People
      summary: Create a person
      description: Create a new person
      parameters:
        - name: data
          in: body
          description: Person to create
          required: True
          schema:
            $ref: '#/definitions/User'
            # type: object
            # properties:
            #   username:
            #     type: string
            #     description: First name of person to create
            #   password:
            #     type: string
            #     description: Last name of person to create
      responses:
        201:
          description: Successfully created person
          schema:
            properties:
              username:
                type: string
                description: First name of person to create
              password:
                type: string
                description: Last name of person to create


definitions:
  User:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      notes:
        type: array
        items:
          type: object
          description: List of all the notes registered by this user

    # Both properties are required
    required:  
      - username
      - password


